name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Setup Rust"
        uses: "actions-rust-lang/setup-rust-toolchain@v1"
      - run: "cargo test"
        working-directory: "rust-sdk/lightspark"
      - run: "cargo fmt --check"
        working-directory: "rust-sdk/lightspark"
      - run: "cargo build"
        working-directory: "rust-sdk/lightspark"

  check:
    if: false
    runs-on: "ubuntu-22.04"
    steps:
      - run: "true"
